micronaut:
  application:
    name: auth-provider
  server:
    http-to-https-redirect: true
    cors:
      enabled: true
  security:
    enabled: true
    redirect:
      enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
trevorism:
  handoff:
    code-lifetime-seconds: 60
    gcp-projects:
      - trevorism
      - trevorism-action
      - trevorism-auth
      - trevorism-billing
      - trevorism-cleo
      - trevorism-data
      - trevorism-draw
      - trevorism-gcloud
      - trevorism-memo
      - trevorism-project
      - trevorism-testing
      - trevorism-trade
