runtime: java17
entrypoint: java -jar auth-provider-all.jar

automatic_scaling:
  min_idle_instances: 1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto